version: "3"
services:
  nextjs-server:
    entrypoint: yarn run dev
    hostname: nextjs-server.my-portfolio
    image: node:20
    user: "1000:1000"
    volumes:
      - ./my-portfolio:/App
    working_dir: /App
