version: "3"
services:
  dev:
    entrypoint: yarn start
    hostname: nextjs-server.my-portfolio
    image: node:20
    user: "1000:1000"
    volumes:
      - ./my-portfolio:/App
    working_dir: /App
  produccion:
    build: ./my-portfolio
    hostname: uae_simulacion-tareas-produccion
    user: "1000:1000"
    #restart: unless-stopped
    working_dir: /App
