version: "3"
services:
  web-dev:
    entrypoint: yarn start
    environment: 
      REACT_APP_API_URL: http://api.nextjs-server.my-portfolio
      REACT_APP_GOOGLE_RECAPTCHA_SIKE_KEY: ...
    hostname: portfolio.71walceli.beauty
    image: node:20
    user: "1000:1000"
    volumes:
      - ./my-portfolio:/App
    working_dir: /App
  api-dev: 
    entrypoint: yarn start
    environment: 
      CORS_ORIGIN: http://portfolio.71walceli.beauty:3000
      AIRTABLE_API_KEY: ...
      AIRTABLE_BASE_ID: ...
      AIRTABLE_TABLE_ID: ...
      GOOGLE_RECAPTCHA_SECRET_KEY: ...
    hostname: api.nextjs-server.my-portfolio
    image: node:20
    user: "1000:1000"
    volumes:
      - ./api:/App
    working_dir: /App
