import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { TranslateProvider } from './translations'
import "node_modules/flag-icons/css/flag-icons.min.css"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />

        <link href="assets/img/favicon.png" rel="icon" />
        <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon" />

        <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
        <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet" />
        <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet" />

        <link href="assets/css/style.css" rel="stylesheet" />

        {/*
          =======================================================
          * Template Name: DevFolio
          * Updated: Sep 18 2023 with Bootstrap v5.3.2
          * Template URL: https://bootstrapmade.com/devfolio-bootstrap-portfolio-html-template/
          * Author: BootstrapMade.com
          * License: https://bootstrapmade.com/license/
          ========================================================
        */}
      </head>

      <body className={inter.className}>
        <TranslateProvider>
          {children}
        </TranslateProvider>
      </body>

      {/* Footer scripts */}
      <script async src="assets/vendor/purecounter/purecounter_vanilla.js"></script>
      <script async src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
      <script async src="assets/vendor/glightbox/js/glightbox.min.js"></script>
      <script async src="assets/vendor/swiper/swiper-bundle.min.js"></script>
      <script async src="assets/vendor/typed.js/typed.umd.js"></script>
      <script async src="assets/vendor/php-email-form/validate.js"></script> 
    </html>
  </>
}
